<a href="https://colab.research.google.com/github/Thanvithmk/deep-learning/blob/main/DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.82.1)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.20.0

In [5]:
#basic libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [6]:
df=pd.read_csv("/content/customer_churn_dataset-training-master.csv")
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [7]:
#Divide the dataset into independent and dependent sets
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [8]:
x

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0
...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0
440829,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0
440830,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0
440831,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0
440832,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0

In [9]:
#Dummy Encoding (drop_first=True) - removes extra col
subs=pd.get_dummies(x["Subscription Type"],drop_first=True)
quat=pd.get_dummies(x["Contract Length"],drop_first=True)
gender=pd.get_dummies(x["Gender"],drop_first=True)

In [10]:
x = x.drop(["Gender","Subscription Type","Contract Length"],axis=1)

In [11]:
x

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction
0,2.0,30.0,39.0,14.0,5.0,18.0,932.00,17.0
1,3.0,65.0,49.0,1.0,10.0,8.0,557.00,6.0
2,4.0,55.0,14.0,4.0,6.0,18.0,185.00,3.0
3,5.0,58.0,38.0,21.0,7.0,7.0,396.00,29.0
4,6.0,23.0,32.0,20.0,5.0,8.0,617.00,20.0
...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,54.0,15.0,1.0,3.0,716.38,8.0
440829,449996.0,25.0,8.0,13.0,1.0,20.0,745.38,2.0
440830,449997.0,26.0,35.0,27.0,1.0,5.0,977.31,9.0
440831,449998.0,28.0,55.0,14.0,2.0,0.0,602.55,2.0
440832,449999.0,31.0,48.0,20.0,1.0,14.0,567.77,21.0

In [12]:
x=pd.concat([x,gender,subs,quat],axis=1)

In [13]:
x

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Male,Premium,Standard,Monthly,Quarterly
0,2.0,30.0,39.0,14.0,5.0,18.0,932.00,17.0,False,False,True,False,False
1,3.0,65.0,49.0,1.0,10.0,8.0,557.00,6.0,False,False,False,True,False
2,4.0,55.0,14.0,4.0,6.0,18.0,185.00,3.0,False,False,False,False,True
3,5.0,58.0,38.0,21.0,7.0,7.0,396.00,29.0,True,False,True,True,False
4,6.0,23.0,32.0,20.0,5.0,8.0,617.00,20.0,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,54.0,15.0,1.0,3.0,716.38,8.0,True,True,False,False,False
440829,449996.0,25.0,8.0,13.0,1.0,20.0,745.38,2.0,False,True,False,False,False
440830,449997.0,26.0,35.0,27.0,1.0,5.0,977.31,9.0,True,False,True,False,True
440831,449998.0,28.0,55.0,14.0,2.0,0.0,602.55,2.0,True,False,True,False,True
440832,449999.0,31.0,48.0,20.0,1.0,14.0,567.77,21.0,True,True,False,False,True

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [16]:
x_train

array([[ 1.70463868, -0.43156119,  1.08604204, ..., -0.71472072,
        -0.4963412 ,  1.22332362],
       [-0.4313211 , -0.51191806, -1.75475233, ..., -0.71472072,
        -0.4963412 ,  1.22332362],
       [ 1.36478109, -0.19049057, -1.11702299, ..., -0.71472072,
        -0.4963412 , -0.81744518],
       ...,
       [-0.80186704, -0.83334554,  0.3323619 , ..., -0.71472072,
        -0.4963412 , -0.81744518],
       [ 1.6788231 , -0.91370241,  0.91211585, ..., -0.71472072,
        -0.4963412 , -0.81744518],
       [ 0.6740076 , -0.35120432, -1.11702299, ..., -0.71472072,
        -0.4963412 , -0.81744518]])

In [17]:
#ANN

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
#from tensorflow.keras.layers import LeakyRelu

In [30]:
classifier=Sequential()

In [31]:
classifier.add(Dense(units=11,activation="relu"))

In [32]:
classifier.add(Dense(units=7,activation="relu"))

In [33]:
classifier.add(Dense(units=6,activation="relu"))

In [34]:
classifier.add(Dense(units=1,activation="sigmoid"))

In [35]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
hist=classifier.fit(x_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
23629/23629 ━━━━━━━━━━━━━━━━━━━━ 92s 4ms/step - accuracy: 0.9875 - loss: 0.0336 - val_accuracy: 0.9949 - val_loss: 0.0130
Epoch 2/100
  216/23629 ━━━━━━━━━━━━━━━━━━━━ 1:24 4ms/step - accuracy: 0.9947 - loss: 0.0135